### ISSUE TITLE
Linux part is not suppporting

### ISSUE THREAD

**Issue by Abk1437** [abhinavrj/Project-Centauri#5]
In our implementation, some Linux part is not working because of the conio.h file is not supported by gcc

**Comment by Abk1437** [comment]
we can use an alternative console I/O library, such as ncurses.

**Comment by abhinavrj** [comment]
Goodmorning It has come to my attention earlier too. We have tried to fix it but haven't been successful. If you find any fix do let us know.On 24-Aug-2021 10:07 am, Abk1437 ***@***.***> wrote:
In our implementation, some Linux part is not working because of the conio.h file is not supported by gcc
